seq_len: 2048
batch_size: 4
pad_token: 0
no_train_label_token: -100
synthetic_tasks_generation_args:
  synthetic_tasks:
  - task_name: concomp_factor
    weight: 1.0
    generation_args:
      task_index: 50
      task_name: concomp_factor_edges_list
      max_nodes: 50
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 10
        min_concomp_size: 3
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 0
          node_to_neighbors_sep: 0
          format: edges_list
  - task_name: concomp_factor
    weight: 1.0
    generation_args:
      task_index: 50
      task_name: concomp_factor_adj_list
      max_nodes: 50
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 10
        min_concomp_size: 3
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: adjacency_list
  - task_name: shortest_path
    weight: 1.0
    generation_args:
      task_index: 51
      task_name: shortest_path_edges_list
      max_nodes: 50
      max_distance: 5
      num_eval_samples: 100
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: edges_list
  - task_name: shortest_path
    weight: 1.0
    generation_args:
      task_index: 51
      task_name: shortest_path_adj_list
      max_nodes: 50
      max_distance: 5
      num_eval_samples: 100
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: adjacency_list
  - task_name: bfs
    weight: 1.0
    generation_args:
      task_index: 52
      task_name: bfs_edges_list
      query_token: 101
      eos_token: 102
      max_nodes: 50
      max_nodes_in_output: 10
      num_eval_samples: 100
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 0
          node_to_neighbors_sep: 0
          format: edges_list
  - task_name: bfs
    weight: 1.0
    generation_args:
      task_index: 52
      task_name: bfs_adj_list
      query_token: 101
      eos_token: 102
      max_nodes: 50
      max_nodes_in_output: 10
      num_eval_samples: 100
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: adjacency_list
  - task_name: bfs
    weight: 1.0
    generation_args:
      task_index: 52
      task_name: bfs_hard_edges_list
      query_token: 101
      eos_token: 102
      max_nodes: 120
      max_nodes_in_output: 20
      num_eval_samples: 100
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 0
          node_to_neighbors_sep: 0
          format: edges_list
  - task_name: bfs
    weight: 1.0
    generation_args:
      task_index: 52
      task_name: bfs_hard_adj_list
      query_token: 101
      eos_token: 102
      max_nodes: 120
      max_nodes_in_output: 20
      num_eval_samples: 100
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: adjacency_list
  - task_name: shortest_path
    weight: 1.0
    generation_args:
      task_index: 51
      task_name: shortest_path_hard_edges_list
      max_nodes: 120
      max_distance: 10
      num_eval_samples: 100
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: edges_list
  - task_name: shortest_path
    weight: 1.0
    generation_args:
      task_index: 51
      task_name: shortest_path_hard_adj_list
      max_nodes: 120
      max_distance: 10
      num_eval_samples: 100
      query_separator_token: 101
      eos_token: 102
      graph_generator_config:
        max_connectivity_components: 5
        min_concomp_size: 5
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: false
        is_dag: false
        edge_probability: 0.02
        encoding_config:
          pair_sep: 301
          node_to_neighbors_sep: 302
          format: adjacency_list
  - task_name: depo
    weight: 1.0
    generation_args:
      task_name: depo_edges_list
      task_index: 53
      max_nodes: 75
      max_hops: 8
      num_queries: 8
      query_token_base: 200
      eos_token: 102
      graph_generator_config:
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: true
        is_dag: true
        edge_probability: 0.5
        encoding_config:
          pair_sep: 25
          node_to_neighbors_sep: 26
          format: edges_list
  - task_name: depo
    weight: 1.0
    generation_args:
      task_name: depo_adj_list
      task_index: 53
      max_nodes: 75
      max_hops: 8
      num_queries: 8
      query_token_base: 200
      eos_token: 102
      graph_generator_config:
        base_vocab_size: 10
        min_token_length: 2
        max_token_length: 4
        is_directed: true
        is_dag: true
        edge_probability: 0.5
        encoding_config:
          pair_sep: 25
          node_to_neighbors_sep: 26
          format: adjacency_list
