#!/bin/bash
set -e

# Eval data is auto-discovered/generated by train.py based on depo_generation_args.
# No need for --regenerate-eval flag.

# Download FineWeb-Edu dataset if requested
if [ "${DOWNLOAD_FINEWEB_EDU}" = "1" ]; then
    DATASET_FRACTION="${DATASET_FRACTION:-1.0}"
    echo "========================================"
    echo "Downloading FineWeb-Edu dataset (fraction: ${DATASET_FRACTION})..."
    echo "========================================"
    python scripts/download_fineweb_edu.py --fraction "${DATASET_FRACTION}"
fi

# Resolve config name (default: depo_debug)
CONFIG_NAME="${CONFIG_NAME:-depo_debug}"
CONFIG_PATH="apps/main/configs/${CONFIG_NAME}.yaml"

# Start training
echo "========================================"
echo "Starting training..."
echo "Config: ${CONFIG_PATH}"
echo "========================================"
cd lingua_modified
python -m apps.main.train config=${CONFIG_PATH}